// SCUM server settings schema. Each category is a list of fields with type/metadata for rendering.
export const SETTINGS_SCHEMA = [
  {
    key: "administration",
    labelKey: "cat_administration",
    icon: "ShieldCheck",
    fields: [
      { key: "ServerName", label: "Server Name", type: "text" },
      { key: "ServerDescription", label: "Description", type: "textarea" },
      { key: "ServerPassword", label: "Server Password", type: "password" },
      { key: "AdminPassword", label: "Admin Password", type: "password" },
      { key: "ServerPort", label: "Game Port", type: "number" },
      { key: "ServerQueryPort", label: "Query Port", type: "number" },
      { key: "MaxPlayers", label: "Max Players", type: "number", min: 1, max: 128 },
      { key: "ReservedSlots", label: "Reserved Slots", type: "number", min: 0 },
      { key: "WelcomeMessage", label: "Welcome Message", type: "text" },
    ],
  },
  {
    key: "world",
    labelKey: "cat_world",
    icon: "Globe",
    fields: [
      { key: "StartingHour", label: "Starting Hour", type: "number", min: 0, max: 23 },
      { key: "TimeOfDayMultiplier", label: "Day Time Multiplier", type: "slider", min: 0.1, max: 10, step: 0.1 },
      { key: "NightTimeMultiplier", label: "Night Time Multiplier", type: "slider", min: 0.1, max: 10, step: 0.1 },
      { key: "WeatherRainMultiplier", label: "Rain Multiplier", type: "slider", min: 0, max: 5, step: 0.1 },
      { key: "TemperatureMultiplier", label: "Temperature Multiplier", type: "slider", min: 0.1, max: 5, step: 0.1 },
      { key: "RespectLocalTimeForSunrise", label: "Respect Local Time for Sunrise", type: "toggle" },
    ],
  },
  {
    key: "economy",
    labelKey: "cat_economy",
    icon: "Coins",
    fields: [
      { key: "TradersEnabled", label: "Traders Enabled", type: "toggle" },
      { key: "TraderFundsMultiplier", label: "Trader Funds Multiplier", type: "slider", min: 0.1, max: 10, step: 0.1 },
      { key: "TraderRestockIntervalHours", label: "Restock Interval (hours)", type: "number", min: 1 },
      { key: "FameOnKill", label: "Fame on Kill", type: "number" },
      { key: "FameOnDeath", label: "Fame on Death", type: "number" },
      { key: "CurrencyBalanceLimit", label: "Currency Limit", type: "number" },
    ],
  },
  {
    key: "loot",
    labelKey: "cat_loot",
    icon: "Package",
    fields: [
      { key: "LootMultiplier", label: "Global Loot", type: "slider", min: 0.1, max: 10, step: 0.1 },
      { key: "ItemSpawningMultiplier", label: "Item Spawning", type: "slider", min: 0.1, max: 10, step: 0.1 },
      { key: "WeaponLootMultiplier", label: "Weapons", type: "slider", min: 0.1, max: 10, step: 0.1 },
      { key: "AmmoLootMultiplier", label: "Ammo", type: "slider", min: 0.1, max: 10, step: 0.1 },
      { key: "MedicineLootMultiplier", label: "Medicine", type: "slider", min: 0.1, max: 10, step: 0.1 },
      { key: "FoodLootMultiplier", label: "Food", type: "slider", min: 0.1, max: 10, step: 0.1 },
      { key: "ClothingLootMultiplier", label: "Clothing", type: "slider", min: 0.1, max: 10, step: 0.1 },
    ],
  },
  {
    key: "vehicles",
    labelKey: "cat_vehicles",
    icon: "Car",
    fields: [
      { key: "VehiclesEnabled", label: "Vehicles Enabled", type: "toggle" },
      { key: "VehicleSpawnMultiplier", label: "Spawn Rate", type: "slider", min: 0.1, max: 10, step: 0.1 },
      { key: "VehicleDurabilityMultiplier", label: "Durability", type: "slider", min: 0.1, max: 10, step: 0.1 },
      { key: "FuelConsumptionMultiplier", label: "Fuel Consumption", type: "slider", min: 0.1, max: 5, step: 0.1 },
      { key: "AllowVehicleStealing", label: "Allow Stealing", type: "toggle" },
    ],
  },
  {
    key: "raid_protection",
    labelKey: "cat_raid_protection",
    icon: "ShieldAlert",
    fields: [
      { key: "BaseRaidingEnabled", label: "Base Raiding Enabled", type: "toggle" },
      { key: "BaseRaidTimesStart", label: "Raid Start (HH:MM)", type: "text" },
      { key: "BaseRaidTimesEnd", label: "Raid End (HH:MM)", type: "text" },
      { key: "BaseDamageMultiplier", label: "Base Damage", type: "slider", min: 0, max: 5, step: 0.1 },
      { key: "LockpickingEnabled", label: "Lockpicking Enabled", type: "toggle" },
    ],
  },
  {
    key: "squads",
    labelKey: "cat_squads",
    icon: "Users",
    fields: [
      { key: "SquadsEnabled", label: "Squads Enabled", type: "toggle" },
      { key: "SquadMaxSize", label: "Max Squad Size", type: "number", min: 1, max: 32 },
      { key: "AllowSquadChat", label: "Squad Chat", type: "toggle" },
      { key: "FriendlyFire", label: "Friendly Fire", type: "toggle" },
    ],
  },
  {
    key: "weapons",
    labelKey: "cat_weapons",
    icon: "Crosshair",
    fields: [
      { key: "WeaponDurabilityMultiplier", label: "Durability", type: "slider", min: 0.1, max: 10, step: 0.1 },
      { key: "AmmoDamageMultiplier", label: "Ammo Damage", type: "slider", min: 0.1, max: 10, step: 0.1 },
      { key: "RecoilMultiplier", label: "Recoil", type: "slider", min: 0, max: 5, step: 0.1 },
      { key: "SwayMultiplier", label: "Sway", type: "slider", min: 0, max: 5, step: 0.1 },
    ],
  },
  {
    key: "zombies_puppets",
    labelKey: "cat_zombies_puppets",
    icon: "Skull",
    fields: [
      { key: "PuppetsEnabled", label: "Puppets Enabled", type: "toggle" },
      { key: "PuppetSpawnMultiplier", label: "Spawn Rate", type: "slider", min: 0, max: 10, step: 0.1 },
      { key: "PuppetDamageMultiplier", label: "Damage", type: "slider", min: 0.1, max: 10, step: 0.1 },
      { key: "PuppetSenseMultiplier", label: "Senses", type: "slider", min: 0.1, max: 10, step: 0.1 },
      { key: "PuppetsRunAtNight", label: "Run at Night", type: "toggle" },
    ],
  },
  {
    key: "players",
    labelKey: "cat_players",
    icon: "User",
    fields: [
      { key: "PlayerDamageMultiplier", label: "Damage Received", type: "slider", min: 0.1, max: 10, step: 0.1 },
      { key: "StaminaMultiplier", label: "Stamina", type: "slider", min: 0.1, max: 10, step: 0.1 },
      { key: "HungerMultiplier", label: "Hunger Rate", type: "slider", min: 0.1, max: 10, step: 0.1 },
      { key: "ThirstMultiplier", label: "Thirst Rate", type: "slider", min: 0.1, max: 10, step: 0.1 },
      { key: "StartingFameOnRespawn", label: "Starting Fame on Respawn", type: "number" },
      { key: "AllowCharacterCreation", label: "Allow Character Creation", type: "toggle" },
    ],
  },
  {
    key: "network",
    labelKey: "cat_network",
    icon: "Network",
    fields: [
      { key: "EnableBattlEye", label: "BattlEye Anti-Cheat", type: "toggle" },
      { key: "EnableRcon", label: "Enable RCON", type: "toggle" },
      { key: "RconPort", label: "RCON Port", type: "number" },
      { key: "RconPassword", label: "RCON Password", type: "password" },
      { key: "EnableAutomaticBackups", label: "Automatic Backups", type: "toggle" },
      { key: "BackupIntervalMinutes", label: "Backup Interval (min)", type: "number", min: 5 },
      { key: "BackupsToKeep", label: "Backups to Keep", type: "number", min: 1 },
    ],
  },
  {
    key: "custom_ini",
    labelKey: "cat_custom_ini",
    icon: "FileCode",
    fields: [
      { key: "ExtraServerSettings", label: "ServerSettings.ini Extras", type: "textarea", rows: 6 },
      { key: "ExtraGameSettings", label: "Game.ini Extras", type: "textarea", rows: 6 },
      { key: "ExtraEngineSettings", label: "Engine.ini Extras", type: "textarea", rows: 6 },
    ],
  },
];
